#!/bin/bash
echo "Checking existence of $1 and $2"
if [ ! -d "$1" ] || [ ! -d "$2" ]; then
echo "Some directory doesn't exist!"
else
echo "Both directories exist!"
limit_value=$(( $3 ))
current=$(df "$1" | grep "$1" | awk '{ print $5}'| sed 's/%//g')
if [ "$current" -gt "$limit_value" ]; then
echo "Percentage of fullness is greater than $limit_value"
num_of_files=0
limit_files=$(( $4 ))
cd "$1"
IFS=$'\n'
for file in $(ls -tr); do
if [ "$num_of_files" -lt "$limit_files" ]; then
tar -rf "$2/backup_log.tar" "$file"
rm "$file"
fi
num_of_files=$(( $num_of_files + 1 ))
done
if [ "$num_of_files" -eq 0 ]; then
echo "No files in $1"
else
gzip  "$2/backup_log.tar"
if [ "$num_of_files" -lt "$limit_files" ]; then
echo "Numbers of files lower than $limit_fles, but percentage of fulness is greater than limit value"
fi
echo "Archive successfully created!"
fi
else
echo "Percentage of fullness is lower than $limit_value"
fi
echo "Ended"
fi
